### ISSUE TITLE
problems executing on windows

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#2026] opened 2024-05-13 06:53 UTC
![IMG_0764](https://github.com/esrlabs/chipmunk/assets/99541/85412b68-7355-4258-9736-a79db58a9b7a)
there seems to be something broken with our signing process on windows

**Comment by DmitryAstafyev** [comment] 2024-05-22 08:33
with the latest windows 11 (with all recent updates) and [3.12.7](https://github.com/esrlabs/chipmunk/releases/tag/3.12.7) I cannot reproduce an issue.

**Comment by itsmesamster** [comment] 2024-05-22 08:50
<img width="426" alt="Screenshot 2024-05-22 at 10 37 57" src="https://github.com/esrlabs/chipmunk/assets/17827621/828624b5-f368-4fbd-b714-7f0e5b049df4">

The issue was reproducible on Accenture systems. This, however, could be resolved with a workaround.
- Open the properties for chipmunk.exe
- Select the checkbox to unblock the executable at the bottom
- Click on Apply
- Close the properties dialogue box.
I checked the same and implemented on my system and also confirmed with the user who raised this issue. It works and the workaround needs to be implemented only once for each new version of chipmunk downloaded from github, if at all required.

This could be permanently resolved by using an "Extended Validation" or "Organization Validation" code signing certificate, instead of the standard code signing certificate.

**Closed** 2024-06-04 14:10 UTC
Labels: bug, windows
