### ISSUE TITLE
keyboard shortcuts invovling SHIFT not working on linux

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#408] opened 2019-08-14 14:04 UTC
# Prerequisites

affected version: 1.18.0

**Comment by DmitryAstafyev** [comment] 2019-09-16 14:19
For a moment we are supporting only one shortcut with shift: `shift + ctrl + F` (opens search tab). 
I'm not able to reproduce this issue with:
* arch-linux
* ubuntu 17.xx
* windows 10
* macos
Do we have logs from the machine there bug was detected? 

I will close this issue and will reopen after some more data will be available:
* platform (mac, win, linux)
* would be great to have logs from `~/.logviewer/logviewer.log`

**Closed by DmitryAstafyev** 2019-09-16 14:19 UTC
Labels: bug
