### ISSUE TITLE
Multiple filter issue

### ISSUE THREAD

**Issue by virendobariya** [esrlabs/chipmunk#2004] opened 2024-04-11 07:09 UTC
**Prerequisites**

affected version:
3.11.2

make sure to check this before filing an issue:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

What did not work as expected?
The scanning of the logs with multiple filters doesn't works on my side. I can just scan for one filter after another.

**Steps to Reproduce**

Please provide detailed steps for reproducing the issue.

**Environment**

version info from chipmunk's about menu

**Failure Logs**

Please include any relevant log snippets or files here.

**Comment by virendobariya** [comment] 2024-04-11 07:23
Issue Solved

**Comment by marcmo** [comment] 2024-04-11 07:32
Hi @virendobariya, thanks for reporting an issue. Could you please shortly describe how you solved the issue?

**Comment by virendobariya** [comment] 2024-04-11 07:39
Actually, it is still unclear. After a complete restart it want to default functionality.

**Comment by DmitryAstafyev** [comment] 2024-04-11 07:42
Hello @virendobariya . Thanks for the report. It would be helpful if you can give us a little bit more insight:
- what do you open? File? Some stream (like TCP, UDP, terminal command)
- what format of source? Text? DLT? SomeIP?
- what kind of filters you are creating? Just filters or maybe filters & charts.

Thanks in advance for the extra-information.

**Comment by virendobariya** [comment] 2024-04-11 07:44
- I opened a terminal command
- The format was TEXT exported from EsoTraceViewer
- Filter and charts both were under search

**Comment by DmitryAstafyev** [comment] 2024-04-11 07:51
@virendobariya and how does the problem look like?
- you've added a couple of filters, you see in the main output indeed some matches, but the search output doesn't include rows with matches? 
- you've added some chart expressions, you see in the main view target content, but in the charts view you don't see any?

If it's possible and your logs don't have sensitive information - the best way would be - share with us problematic peace of logs (you can export it as text file) and filters, which you are using. In this case we will have a strong way to reproduce issue and resolve it.

**Comment by DmitryAstafyev** [comment] 2024-04-11 07:55
@virendobariya also take into account: even if you have some filters are created (which you are seeing in right sidebar, tab "Filters"); if you have in same time some `active` filter (filter, which you are seeing in input of search) - in this case in search output you will see **only** `active` search. If you have `active` search, your filters in sidebar are **ignored**.

**Comment by virendobariya** [comment] 2024-04-11 08:02
The problem: 
**you've added a couple of filters, you see in the main output indeed some matches, but the search output doesn't include rows with matches?** applies in my case.

**Comment by virendobariya** [comment] 2024-04-11 08:04
Right now as it is working well enough, it is not possible to show the error at the moment. I will get back to you if the problem persists in future with an exact overview including screenshots.

**Comment by DmitryAstafyev** [comment] 2024-04-11 11:09
@virendobariya 

> Right now as it is working well enough, it is not possible to show the error at the moment. I will get back to you if the problem persists in future with an exact overview including screenshots.

I'm closing issue right now, because isn't confirmed. If you will got this issue again, please reopen it. And once again thanks!

**Closed by DmitryAstafyev** 2024-04-11 11:09 UTC
Labels: new
