### ISSUE TITLE
Filters/Charts Problems

### ISSUE THREAD

**Issue by marcmo** [esrlabs/chipmunk#1772] opened 2023-04-25 15:13 UTC
* [x] editing of filters not possible (@DmitryAstafyev)
![edit_filters](https://user-images.githubusercontent.com/99541/234309063-aba2edff-0e6e-4edc-94cd-e2031bef5d48.gif)
* [x]  long filters hide checkmark and color (@DmitryAstafyev)
<img width="263" alt="image" src="https://user-images.githubusercontent.com/99541/234309504-59c4281b-c0d9-4fa9-9b23-ddca9ceff14a.png">

* [x] vertical scale needed, chart values seem to go missing...but we just adapt the scale (@fur-gan)

![missing_chart_values](https://user-images.githubusercontent.com/99541/234311105-301479f7-0f6d-4f00-a23b-0e1692831372.gif)
* [x] after resizing we lost some space to the right (@fur-gan)

![after_resizing_missing_movment](https://user-images.githubusercontent.com/99541/234312147-053f93aa-d887-43a6-9442-5c305cb0ad16.gif)
* [x] dashed white line needs to show up in main chart view (@fur-gan)
![white_line](https://user-images.githubusercontent.com/99541/234315950-4a136251-fc2c-4533-9790-25d4fc9a939b.gif)
* [ ] selection needs to be possible with mouse drag (@fur-gan)
![selection_in_overview](https://user-images.githubusercontent.com/99541/234318067-74a16405-07d1-416f-90b8-a959eab054c3.gif)
* [x] yellow legend is only shown to the side and always with pink legend (@fur-gan)
![legend](https://user-images.githubusercontent.com/99541/234319907-bdbbcd06-a820-4035-8198-84f4ad390418.gif)
* [ ] missing focus in search field when hitting the `/` shortcut (works only on 2nd `/` (@DmitryAstafyev)
![missing_focus](https://user-images.githubusercontent.com/99541/234322399-c6784e8d-aa2e-4ca8-9943-2f35e42ba4c6.gif)
* [x] sometimes the content in main view is missing (@fur-gan)
![missing_graph](https://user-images.githubusercontent.com/99541/234323843-25cccbda-d377-48f3-9b5f-014b47c991ce.gif)

**Comment by fur-gan** [comment] 2023-05-08 09:18
> missing focus in search field when hitting the / shortcut
Duplicate of #1779 

> selection needs to be possible with mouse drag
Duplicate of #1600

**Closed** 2023-06-04 13:26 UTC
Labels: bug
