### ISSUE TITLE
Export 

### ISSUE THREAD

**Issue by Benedikt24** [esrlabs/chipmunk#1977] opened 2024-02-05 09:39 UTC
**Prerequisites**

affected version:
3.10.2
make sure to check this before filing an issue:

- [x ] I am running the latest version
- [ ] I checked to make sure that this issue has not already been filed

**Describe the issue**
I can't save the recorded file
What did not work as expected?
Save files to the desktop
**Steps to Reproduce**
ADB Recording 
Please provide detailed steps for reproducing the issue.

**Environment**

version info from chipmunk's about menu

**Failure Logs**

Please include any relevant log snippets or files here.

**Comment by DmitryAstafyev** [comment] 2024-02-06 15:28
Hello @Benedikt24 thanks for reporting this issue.

I've tried to reproduce the issue and cannot do it. 

Could you please provide some additional information or correct me with my guesses:

- you got some adb logcat stream
- you selected some rows to export (probably with holded SHIFT+CLICK)
- you called the context menu and select "Export xx rows"

Did you get a dialog to select the destination file? If a file has been selected, was it saved?

**Comment by DmitryAstafyev** [comment] 2024-04-11 11:13
@Benedikt24 I would close this issue, because no any addition insight and no way to reproduce/confirm issue. Please reopen it with some extra-information.

**Closed by DmitryAstafyev** 2024-04-11 11:13 UTC
Labels: approving
