### ISSUE TITLE
Chipmunk not closing properly

### ISSUE THREAD

**Issue by fur-gan** [esrlabs/chipmunk#901] opened 2020-09-03 19:25 UTC
**Prerequisites**

affected version:

- [x] I am running the latest version
- [x] I checked to make sure that this issue has not already been filed

**Describe the issue**

Chipmunk tasks still running when application closed

**Steps to Reproduce**

- Open Chipmunk
- Open .dlt file
- Close Chipmunk while loading file

**Failure Logs**

```
...
[1599160091543][     0ms][  DEBUG][Application]: Destroy: ServiceFileWriter: DONE
[1599160091543][     0ms][  DEBUG][Application]: Destroy: ServiceTimestampFormatRecent: DONE
[1599160091543][     0ms][  DEBUG][Application]: Destroy: ServiceDLTDeamonConnector: DONE
[1599160091543][     0ms][  DEBUG][Global]: shutdown was requested
[1599160091543][     0ms][  DEBUG][Global]: shutdown request is accepted
[1599160091619][   +76ms][  DEBUG][Global]: >>> error on promise poll: Error: (receiving in channels.rs): Channel was Disconnected
[1599160091620][    +1ms][  DEBUG][Global]: [BAD] UnhandledRejection: (receiving in channels.rs): Channel was Disconnected
[1599160091620][     0ms][  ERROR][Application]: [BAD] UnhandledRejection: (receiving in channels.rs): Channel was Disconnected
```
[chipmunk.log](https://github.com/esrlabs/chipmunk/files/5170759/chipmunk.log)

**Comment by fur-gan** [comment] 2020-09-03 19:27
![Anmerkung 2020-09-03 212626](https://user-images.githubusercontent.com/56543045/92158526-53325280-ee2c-11ea-8289-6f23a5f19ae6.png)

**Comment by marcmo** [comment] 2020-11-05 09:30
duplicate of #784

**Closed by marcmo** 2020-11-05 09:30 UTC
Labels: new
